language: node_js

node_js:
  - stable

install:
  - npm install

script:
  - npm run cover

services:
  - mysql

env:
  - ANY_DB_Q_TEST_MYSQL=1
  - ANY_DB_Q_TEST_MYSQL_DATABASE=any_db_q_test

# Send coverage data to Coveralls
after_script: "cat coverage/lcov.info | node_modules/coveralls/bin/coveralls.js"
