language: node_js

node_js:
  - stable

install:
  - npm install

script:
  - npm run cover

services:
  - mysql

env:
  - DBCP_TEST_MYSQL=1 DBCP_TEST_MYSQL_DATABASE=db_connection_promise_test

# Send coverage data to Coveralls
after_script: "cat coverage/lcov.info | node_modules/coveralls/bin/coveralls.js"
